modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
[[mods]]
modId="moremekanismprocessing"
version="${file.jarVersion}"
displayName="More Mekanism Processing"
credits="gisellevonbingen"
authors="gisellevonbingen"
description='''
Add mekanism's ore processing to other mod's ores
'''
[[dependencies.moremekanismprocessing]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moremekanismprocessing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moremekanismprocessing]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.1.1,)"
    ordering="AFTER"
    side="BOTH"
