modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="moremekanismprocessing"
version="${file.jarVersion}"
displayName="More Mekanism Processing"
credits="gisellevonbingen"
authors="gisellevonbingen"
description='''
Add mekanism's ore processing to other mod's ores
'''
[[dependencies.moremekanismprocessing]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moremekanismprocessing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moremekanismprocessing]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.0.20,)"
    ordering="AFTER"
    side="BOTH"
